api_version = "2026-01"

[[extensions]]
name = "bundle-discount"
handle = "bundle-discount"

uid = "208e9edf-8b9b-6b74-3f3a-539fdede2328f859a084"

type = "function"
description = "Validates complete bundle presence in cart before applying discount"

[extensions.build]
command = "npx tsc && npx esbuild dist/index.js --bundle --outfile=dist/function.js --platform=node --format=esm --target=esnext"
path = "dist/function.js"
watch = ["src/**/*.ts"]

[[extensions.targeting]]
target = "purchase.product-discount.run"
input_query = "src/run.graphql"
export = "default"

[extensions.ui]
enable_create = false

[[extensions.metafields]]
namespace = "shopibundle"
key = "bundle_config"
